### ISSUE TITLE
Freaze on location file update

### ISSUE THREAD

**Issue by pshnn** [airblade/vim-localorie#4]
After I save changes to my locale files vim freeze for some time (1-2 sec) before unfreezing back. I think this is happening because I have large amount of translation files.
Is there any recommendations on how to handle such situations?
Thanks!

**Comment by airblade** [comment]
Whenever you save any locale files the plugin re-reads all of them:

https://github.com/airblade/vim-localorie/blob/8ea9b956269d55f0b33382f52dc1e79945e5785e/plugin/localorie.vim#L15

I could add some logic to only discard and re-process the files which have changed - but a simple workaround would be to remove the autocmd, either via a new option or via an after/ config, and then explicitly re-load the files only when you want.

(I’m away and won’t be able to make any code changes until I’m back.)

**Comment by pshnn** [comment]
So I disabled localorie BufWritePost events by doing `autocmd! localorie` or `autocmd! localorie BufWritePost` in opened vim and also I was able to map `load_translations()` function in my .vimrc but for some reason I can't disable auto command from my .vimrc.
When I add `autocmd! localorie` or `autocmd! localorie BufWritePost` to my .vimrc and open my vim I see this error:
```
E216: No such group or event: localorie
```

Do you have any ideas why I can't do this or why is this happening?

**Comment by airblade** [comment]
Yes, your vimrc is read before any plugins are loaded.  To get around this, create an after/ directory beside your vimrc and put your autocmd! in a file in there.

**Comment by pshnn** [comment]
Thank you, I made it work.

Just for history:
I created a file `~/.vim/after/plugin/vim-localorie.vim` with this content:
```
autocmd! localorie BufWritePost
```

Should I create a PR with README.md update for this scenario or you will fix it in the future updates?

**Comment by airblade** [comment]
I’ll address this in an update when I’m back at my desk.  Thanks for the offer!

**Comment by airblade** [comment]
I have just updated the code with a different approach: everything remains automatic but only the locale file you save gets reprocessed, instead of all of them.

(The first time you look up a translation, all locale files will be processed.  This remains the same.  I can't think of a way to optimise this.)
