### ISSUE TITLE
Support for i18n angular translation

### ISSUE THREAD

**Issue by jugarpeupv** [airblade/vim-localorie#6]
Hi, this plugin is awesome, a good idea would be to add support for angular. I have been searching for a vim/neovim i18n plugin but couldnt find one. In vscode there is i18n ally which makes this awesome feature of inline translate keys in html template like in this image. Wold it be possible to add support for this?

<img width="773" alt="image" src="https://user-images.githubusercontent.com/69123204/163728455-85b6829e-0b87-4672-b489-8fef7622c290.png">

**Comment by airblade** [comment]
Thanks for the suggestion.

I have never used Angular and so wouldn't know how best to resolve the inevitable trade-offs which arise when building something.  I also don't want to maintain and support software I don't use, so I'm going to decline.  Sorry!
